### ISSUE TITLE
Docs outdated

### ISSUE THREAD

**Issue by UVLabs** [soflyy/wp-all-import-rapid-addon#6]
I think your docs are outdated, can't get any field to show with simple code as:

```
<?php
include "rapid-addon.php";

$wcdpue_addon = new RapidAddon('WCDPUE Add-on', 'wcdpue-addon');
$wcdpue_addon->add_field('wcdpue_product_id', 'WooCommerce Product ID', 'text');
```
To show any field on the import setting up page. Your docs have the same code but it doesn't work:

http://www.wpallimport.com/documentation/addon-dev/structure/

**Comment by UVLabs** [comment]
@cmdmcs

**Comment by trey8611** [comment]
Hi @UVLabs 

You need to specify when your add-on runs in order for it to show up during the import. Since this is a WooCommerce add-on, you should run it for product imports like so:

`$wcdpue_addon->run( array(
    "post_types" => array( "product" )
  )
);`

And, to import the actual data, you'd need to use 'set_import_function' and write the import function. See this full example: https://paste.ee/p/zDfaZ.

That being said, there are some things in the docs that are outdated, and we will be updating them as soon as possible.
